//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeExam.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contest
    {
        public int ContestID { get; set; }
        public Nullable<int> ExamID { get; set; }
        public string ContestText { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<bool> IsTeacherResponse { get; set; }
        public string TeacherResponse { get; set; }
        public Nullable<int> DesingerID { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
