//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeExam.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam()
        {
            this.Participant = new HashSet<Participant>();
            this.QuestionExam = new HashSet<QuestionExam>();
            this.StudentExamPermision = new HashSet<StudentExamPermision>();
        }
    
        public int ExamID { get; set; }
        public string ExamName { get; set; }
        public string Level { get; set; }
        public Nullable<int> ChapterID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public string QuestionType { get; set; }
        public string ExamType { get; set; }
        public string SupervisorName { get; set; }
        public Nullable<int> RepeatTestCount { get; set; }
        public Nullable<int> OptionalQuestionCount { get; set; }
        public Nullable<double> OptionalQuestionScore { get; set; }
        public Nullable<int> DescriptionQuestionCount { get; set; }
        public Nullable<double> DescriptionQuestionScore { get; set; }
        public Nullable<int> BlankQuestionCount { get; set; }
        public Nullable<double> BlankQuestionScore { get; set; }
        public Nullable<int> TrueFalseQuestionCount { get; set; }
        public Nullable<double> TrueFalseQuestionScore { get; set; }
        public Nullable<int> PracticalQuestionCount { get; set; }
        public Nullable<double> PracticalQuestionScore { get; set; }
        public Nullable<double> TotalScore { get; set; }
        public string Status { get; set; }
        public string Difficulty { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> DelayTime { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant> Participant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionExam> QuestionExam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentExamPermision> StudentExamPermision { get; set; }
    }
}
