//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeExam.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.QuestionExam = new HashSet<QuestionExam>();
        }
    
        public int QuestionID { get; set; }
        public Nullable<int> DesignerID { get; set; }
        public Nullable<int> ChapterID { get; set; }
        public string QuestionType { get; set; }
        public string Difficulty { get; set; }
        public Nullable<int> BookPage { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string TextQuestion { get; set; }
        public Nullable<int> DisplayCount { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public string LanguageDirection { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        public virtual Designer Designer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionExam> QuestionExam { get; set; }
    }
}
