//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeExam.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegsiterClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegsiterClass()
        {
            this.StudentClass = new HashSet<StudentClass>();
        }
    
        public int RegisterClassID { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> LessonID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public string Descritption { get; set; }
        public string Day { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClass> StudentClass { get; set; }
    }
}
